/*
 *
 * DashboardPage constants
 *
 */

export const GET_NAME = 'app/DashboardPage/GET_NAME';
export const GET_NAME_SUCCESS = 'app/DashboardPage/GET_NAME_SUCCESS';
export const GET_NAME_ERROR = 'app/DashboardPage/GET_NAME_ERROR';

export const GET_SURNAME = 'app/DashboardPage/GET_SURNAME';
export const GET_SURNAME_SUCCESS = 'app/DashboardPage/GET_SURNAME_SUCCESS';
export const GET_SURNAME_ERROR = 'app/DashboardPage/GET_SURNAME_ERROR';

export const GET_CURRENCY = 'app/DashboardPage/GET_CURRENCY';
export const GET_CURRENCY_SUCCESS = 'app/DashboardPage/GET_CURRENCY_SUCCESS';
export const GET_CURRENCY_ERROR = 'app/DashboardPage/GET_CURRENCY_ERROR';

export const GET_EMAIL = 'app/DashboardPage/GET_EMAIL';
export const GET_EMAIL_SUCCESS = 'app/DashboardPage/GET_EMAIL_SUCCESS';
export const GET_EMAIL_ERROR = 'app/DashboardPage/GET_EMAIL_ERROR';

export const GET_LAST_PRESENT_LOGGED =
  'app/DashboardPage/GET_LAST_PRESENT_LOGGED';
export const GET_LAST_PRESENT_LOGGED_SUCCESS =
  'app/DashboardPage/GET_LAST_PRESENT_LOGGED_SUCCESS';
export const GET_LAST_PRESENT_LOGGED_ERROR =
  'app/DashboardPage/GET_LAST_PRESENT_LOGGED_ERROR';

export const GET_LAST_FAILED_LOGGED =
  'app/DashboardPage/GET_LAST_FAILED_LOGGED';
export const GET_LAST_FAILED_LOGGED_SUCCESS =
  'app/DashboardPage/GET_LAST_FAILED_LOGGED_SUCCESS';
export const GET_LAST_FAILED_LOGGED_ERROR =
  'app/DashboardPage/GET_LAST_FAILED_LOGGED_ERROR';

export const GET_LAST_SUCCESSFUL_LOGGED =
  'app/DashboardPage/GET_LAST_SUCCESSFUL_LOGGED';
export const GET_LAST_SUCCESSFUL_LOGGED_SUCCESS =
  'app/DashboardPage/GET_LAST_SUCCESSFUL_LOGGED_SUCCESS';
export const GET_LAST_SUCCESSFUL_LOGGED_ERROR =
  'app/DashboardPage/GET_LAST_SUCCESSFUL_LOGGED_ERROR';

export const GET_AVAILABLE_FUNDS = 'app/DashboardPage/GET_AVAILABLE_FUNDS';
export const GET_AVAILABLE_FUNDS_SUCCESS =
  'app/DashboardPage/GET_AVAILABLE_FUNDS_SUCCESS';
export const GET_AVAILABLE_FUNDS_ERROR =
  'app/DashboardPage/GET_AVAILABLE_FUNDS_ERROR';

export const GET_ACCOUNT_BILLS = 'app/DashboardPage/GET_ACCOUNT_BILLS';
export const GET_ACCOUNT_BILLS_SUCCESS =
  'app/DashboardPage/GET_ACCOUNT_BILLS_SUCCESS';
export const GET_ACCOUNT_BILLS_ERROR =
  'app/DashboardPage/GET_ACCOUNT_BILLS_ERROR';

export const GET_ACCOUNT_BALANCE_HISTORY =
  'app/DashboardPage/GET_ACCOUNT_BALANCE_HISTORY';
export const GET_ACCOUNT_BALANCE_HISTORY_SUCCESS =
  'app/DashboardPage/GET_ACCOUNT_BALANCE_HISTORY_SUCCESS';
export const GET_ACCOUNT_BALANCE_HISTORY_ERROR =
  'app/DashboardPage/GET_ACCOUNT_BALANCE_HISTORY_ERROR';

export const GET_SAVINGS = 'app/DashboardPage/GET_SAVINGS';
export const GET_SAVINGS_SUCCESS = 'app/DashboardPage/GET_SAVINGS_SUCCESS';
export const GET_SAVINGS_ERROR = 'app/DashboardPage/GET_SAVINGS_ERROR';

export const GET_RECENT_TRANSACTIONS_SENDER =
  'app/DashboardPage/GET_RECENT_TRANSACTIONS_SENDER';
export const GET_RECENT_TRANSACTIONS_SENDER_SUCCESS =
  'app/DashboardPage/GET_RECENT_TRANSACTIONS_SENDER_SUCCESS';
export const GET_RECENT_TRANSACTIONS_SENDER_ERROR =
  'app/DashboardPage/GET_RECENT_TRANSACTIONS_SENDER_ERROR';

export const GET_RECENT_TRANSACTIONS_RECIPIENT =
  'app/DashboardPage/GET_RECENT_TRANSACTIONS_RECIPIENT';
export const GET_RECENT_TRANSACTIONS_RECIPIENT_SUCCESS =
  'app/DashboardPage/GET_RECENT_TRANSACTIONS_RECIPIENT_SUCCESS';
export const GET_RECENT_TRANSACTIONS_RECIPIENT_ERROR =
  'app/DashboardPage/GET_RECENT_TRANSACTIONS_RECIPIENT_ERROR';

export const GET_OUTGOING_TRANSFERS_SUM =
  'app/DashboardPage/GET_OUTGOING_TRANSFERS_SUM';
export const GET_OUTGOING_TRANSFERS_SUM_SUCCESS =
  'app/DashboardPage/GET_OUTGOING_TRANSFERS_SUM_SUCCESS';
export const GET_OUTGOING_TRANSFERS_SUM_ERROR =
  'app/DashboardPage/GET_OUTGOING_TRANSFERS_SUM_ERROR';

export const GET_INCOMING_TRANSFERS_SUM =
  'app/DashboardPage/GET_INCOMING_TRANSFERS_SUM';
export const GET_INCOMING_TRANSFERS_SUM_SUCCESS =
  'app/DashboardPage/GET_INCOMING_TRANSFERS_SUM_SUCCESS';
export const GET_INCOMING_TRANSFERS_SUM_ERROR =
  'app/DashboardPage/GET_INCOMING_TRANSFERS_SUM_ERROR';
