export const PHONE_LANDSCAPE_VIEWPORT_WIDTH = '480px';
export const TABLET_VIEWPORT_WIDTH = '768px';
export const TABLET_LANDSCAPE_VIEWPORT_WIDTH = '1024px';
export const DESKTOP_VIEWPORT_WIDTH = '1260px';

export const HIDDEN_TOOLBAR_TITLE_VIEWPORT_WIDTH = '696px';
export const TOGGLE_TOOLBAR_VIEWPORT_WIDTH = '660px';
