/*
 *
 * App constants
 *
 */

export const LOGGED_IN = 'app/App/LOGGED_IN';
export const IS_LOGGED = 'app/App/IS_LOGGED';

export const LOGOUT = 'app/App/LOGOUT';
export const LOGOUT_SUCCESS = 'app/App/LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'app/App/LOGOUT_ERROR';

export const TOGGLE_NAVIGATION_DESKTOP = 'app/App/TOGGLE_NAVIGATION_DESKTOP';
export const TOGGLE_NAVIGATION_MOBILE = 'app/App/TOGGLE_NAVIGATION_MOBILE';
export const TOGGLE_MESSAGES = 'app/App/TOGGLE_MESSAGES';
export const TOGGLE_NOTIFICATIONS = 'app/App/TOGGLE_NOTIFICATIONS';

export const CHECK_NEW_MESSAGES = 'app/App/CHECK_NEW_MESSAGES';
export const CHECK_NEW_MESSAGES_SUCCESS = 'app/App/CHECK_NEW_MESSAGES_SUCCESS';
export const CHECK_NEW_MESSAGES_ERROR = 'app/App/CHECK_NEW_MESSAGES_ERROR';

export const CHECK_NEW_NOTIFICATIONS = 'app/App/CHECK_NEW_NOTIFICATIONS';
export const CHECK_NEW_NOTIFICATIONS_SUCCESS =
  'app/App/CHECK_NEW_NOTIFICATIONS_SUCCESS';
export const CHECK_NEW_NOTIFICATIONS_ERROR =
  'app/App/CHECK_NEW_NOTIFICATIONS_ERROR';

export const GET_NEW_NOTIFICATIONS = 'app/App/GET_NEW_NOTIFICATIONS';
export const GET_NEW_NOTIFICATIONS_SUCCESS =
  'app/App/GET_NEW_NOTIFICATIONS_SUCCESS';
export const GET_NEW_NOTIFICATIONS_ERROR =
  'app/App/GET_NEW_NOTIFICATIONS_ERROR';

export const ENQUEUE_SNACKBAR = 'app/App/ENQUEUE_SNACKBAR';
export const CLOSE_SNACKBAR = 'app/App/CLOSE_SNACKBAR';
export const REMOVE_SNACKBAR = 'app/App/REMOVE_SNACKBAR';
