/*
 *
 * PaymentPage constants
 *
 */

export const DEFAULT_ACTION = 'app/PaymentPage/DEFAULT_ACTION';

export const CHANGE_ACCOUNT_NUMBER = 'app/PaymentPage/CHANGE_ACCOUNT_NUMBER';
export const ENTER_ACCOUNT_NUMBER = 'app/PaymentPage/ENTER_ACCOUNT_NUMBER';
export const ENTER_ACCOUNT_NUMBER_SUCCESS =
  'app/PaymentPage/ENTER_ACCOUNT_NUMBER_SUCCESS';
export const ENTER_ACCOUNT_NUMBER_ERROR =
  'app/PaymentPage/ENTER_ACCOUNT_NUMBER_ERROR';

export const SEARCH_ACCOUNT_BILLS = 'app/PaymentPage/SEARCH_ACCOUNT_BILLS';
export const SEARCH_ACCOUNT_BILLS_SUCCESS =
  'app/PaymentPage/SEARCH_ACCOUNT_BILLS_SUCCESS';
export const SEARCH_ACCOUNT_BILLS_ERROR =
  'app/PaymentPage/SEARCH_ACCOUNT_BILLS_ERROR';
export const CLEAR_ACCOUNT_BILLS = 'app/PaymentPage/CLEAR_ACCOUNT_BILLS';

export const CHANGE_AMOUNT_MONEY = 'app/PaymentPage/CHANGE_AMOUNT_MONEY';
export const ENTER_AMOUNT_MONEY = 'app/PaymentPage/ENTER_AMOUNT_MONEY';
export const ENTER_AMOUNT_MONEY_SUCCESS =
  'app/PaymentPage/ENTER_AMOUNT_MONEY_SUCCESS';
export const ENTER_AMOUNT_MONEY_ERROR =
  'app/PaymentPage/ENTER_AMOUNT_MONEY_ERROR';

export const CHANGE_TRANSFER_TITLE = 'app/PaymentPage/CHANGE_TRANSFER_TITLE';
export const ENTER_TRANSFER_TITLE = 'app/PaymentPage/ENTER_TRANSFER_TITLE';
export const ENTER_TRANSFER_TITLE_SUCCESS =
  'app/PaymentPage/ENTER_TRANSFER_TITLE_SUCCESS';
export const ENTER_TRANSFER_TITLE_ERROR =
  'app/PaymentPage/ENTER_TRANSFER_TITLE_ERROR';

export const SEND_AUTHORIZATION_KEY = 'app/PaymentPage/SEND_AUTHORIZATION_KEY';
export const SEND_AUTHORIZATION_KEY_SUCCESS =
  'app/PaymentPage/SEND_AUTHORIZATION_KEY_SUCCESS';
export const SEND_AUTHORIZATION_KEY_ERROR =
  'app/PaymentPage/SEND_AUTHORIZATION_KEY_ERROR';

export const CHANGE_AUTHORIZATION_KEY =
  'app/PaymentPage/CHANGE_AUTHORIZATION_KEY';
export const ENTER_AUTHORIZATION_KEY =
  'app/PaymentPage/ENTER_AUTHORIZATION_KEY';
export const ENTER_AUTHORIZATION_KEY_SUCCESS =
  'app/PaymentPage/ENTER_AUTHORIZATION_KEY_SUCCESS';
export const ENTER_AUTHORIZATION_KEY_ERROR =
  'app/PaymentPage/ENTER_AUTHORIZATION_KEY_ERROR';

export const GET_CURRENCY = 'app/PaymentPage/GET_CURRENCY';
export const GET_CURRENCY_SUCCESS = 'app/PaymentPage/GET_CURRENCY_SUCCESS';
export const GET_CURRENCY_ERROR = 'app/PaymentPage/GET_CURRENCY_ERROR';

export const GET_AUTHORIZATION_KEY = 'app/PaymentPage/GET_AUTHORIZATION_KEY';
export const GET_AUTHORIZATION_KEY_SUCCESS =
  'app/PaymentPage/GET_AUTHORIZATION_KEY_SUCCESS';
export const GET_AUTHORIZATION_KEY_ERROR =
  'app/PaymentPage/GET_AUTHORIZATION_KEY_ERROR';

export const MAKE_PAYMENT = 'app/PaymentPage/MAKE_PAYMENT';
export const MAKE_PAYMENT_SUCCESS = 'app/PaymentPage/MAKE_PAYMENT_SUCCESS';
export const MAKE_PAYMENT_ERROR = 'app/PaymentPage/MAKE_PAYMENT_ERROR';

export const PAYMENT_STEP_NEXT = 'app/PaymentPage/PAYMENT_STEP_NEXT';
export const PAYMENT_STEP_BACK = 'app/PaymentPage/PAYMENT_STEP_BACK';
